# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'RealmSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealmSwiftDemo
  pod 'RealmSwift', '10.41.1'
end
